<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NetCommerce.Ordering.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Kernel\NetCommerce.Kernel.Core\NetCommerce.Kernel.Core.csproj"/>
    <ProjectReference Include="..\..\Domain.Shared\NetCommerce.Domain.Shared\NetCommerce.Domain.Shared.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Analyzer Include="..\..\..\artifacts\bin\NetCommerce.Kernel.SourceGenerators\$(Configuration)\NetCommerce.Kernel.SourceGenerators.dll"/>
  </ItemGroup>

</Project>
