<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NetCommerce.Media.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WolverineFx"/>
    <PackageReference Include="FluentValidation"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Kernel\NetCommerce.Kernel.Application\NetCommerce.Kernel.Application.csproj"/>
  </ItemGroup>

</Project>
