<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NetCommerce.SharedKernel.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational"/>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
    <PackageReference Include="StackExchange.Redis"/>
    <PackageReference Include="RedLock.net"/>
    <PackageReference Include="WolverineFx"/>
    <PackageReference Include="WolverineFx.EntityFrameworkCore"/>
    <PackageReference Include="WolverineFx.Postgresql"/>
    <PackageReference Include="WolverineFx.FluentValidation"/>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions"/>
    <PackageReference Include="Microsoft.Extensions.Http.Resilience"/>
    <PackageReference Include="Polly"/>
    <PackageReference Include="Polly.Extensions"/>
    <PackageReference Include="Serilog"/>
    <PackageReference Include="Serilog.Extensions.Logging"/>
    <PackageReference Include="WolverineFx.SignalR"/>
    <PackageReference Include="Asp.Versioning.Mvc"/>
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharedKernel\SharedKernel.csproj"/>
    <ProjectReference Include="..\..\Kernel\NetCommerce.Kernel.Compliance\NetCommerce.Kernel.Compliance.csproj"/>
  </ItemGroup>

</Project>
