<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NetCommerce.Finance.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Finance.Application\Finance.Application.csproj"/>
    <ProjectReference Include="..\Finance.Domain\Finance.Domain.csproj"/>
    <ProjectReference Include="..\..\Payments\Payments.Domain\Payments.Domain.csproj"/>
    <ProjectReference Include="..\..\Payments\Payments.Infrastructure\Payments.Infrastructure.csproj"/>
    <ProjectReference Include="..\..\Kernel.Adapters\NetCommerce.Kernel.EfCore\NetCommerce.Kernel.EfCore.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore"/>
    <PackageReference Include="WolverineFx.EntityFrameworkCore"/>
  </ItemGroup>

</Project>
