<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Kernel.Adapters\NetCommerce.Kernel.EfCore\NetCommerce.Kernel.EfCore.csproj"/>
    <ProjectReference Include="..\..\Shared\SharedKernel\SharedKernel.csproj"/>
    <ProjectReference Include="..\Ordering.Application\Ordering.Application.csproj"/>
  </ItemGroup>

</Project>
