<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NetCommerce.Inventory.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WolverineFx"/>
    <PackageReference Include="FluentValidation"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Inventory.Domain\Inventory.Domain.csproj"/>
    <ProjectReference Include="..\..\Kernel\NetCommerce.Kernel.Application\NetCommerce.Kernel.Application.csproj"/>
    <ProjectReference Include="..\..\Domain.Shared\NetCommerce.Domain.Shared\NetCommerce.Domain.Shared.csproj"/>
  </ItemGroup>

</Project>
