<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NetCommerce.Inventory.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="FluentValidation" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Inventory.Domain\Inventory.Domain.csproj" />
    <ProjectReference Include="..\..\Shared\SharedKernel\SharedKernel.csproj" />
  </ItemGroup>

</Project>
