<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NetCommerce.Payments.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Payments.Domain\Payments.Domain.csproj" />
    <ProjectReference Include="..\..\Shared\SharedKernel\SharedKernel.csproj" />
  </ItemGroup>

</Project>
