<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NetCommerce.Basket.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Basket.Application\Basket.Application.csproj" />
    <ProjectReference Include="..\..\Shared\SharedKernel\SharedKernel.csproj" />
    <ProjectReference Include="..\..\Shared\SharedKernel.Infrastructure\SharedKernel.Infrastructure.csproj" />
  </ItemGroup>

</Project>
