<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NetCommerce.Basket.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Basket.Application\Basket.Application.csproj"/>
    <ProjectReference Include="..\..\Kernel.Adapters\NetCommerce.Kernel.EfCore\NetCommerce.Kernel.EfCore.csproj"/>
  </ItemGroup>

</Project>
